apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s
spec:
  selector:
    matchLabels:
      app: springboot-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s
    spec:
      containers:
        - name: springboot-k8s
          image: shadabgada/demo:1.0
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: springboot-k8s
  labels:
    name: springboot-k8s
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-k8s
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-message.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-k8s
                port:
                  number: 8080